apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-p3
  template:
    metadata:
      labels:
        app: app-p3
    spec:
      containers:
      - name: app-p3
        image: wil42/playground:v2 # edit tag to test argoCD
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-p3
  ports:
    - port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: argo-app.com
    http:
      paths:
      - backend:
          service:
            name: app-service
            port:
              number: 8888
        path: /
        pathType: Prefix
